# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentFirstName', models.CharField(blank=True, max_length=100)),
                ('studentLastName', models.CharField(blank=True, max_length=100)),
                ('studentBirthDate', models.DateField(blank=True, null=True)),
                ('studentBio', models.TextField(blank=True, max_length=500)),
                ('studentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
