# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentUser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
