# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170320_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentBirthDate',
            new_name='BirthDate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentFirstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentLastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentUser',
            new_name='StudentNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentBio',
        ),
        migrations.AddField(
            model_name='student',
            name='ContactNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='EmailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='MunicipalityAddress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Province_CityAddress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='StreetAddress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='UserName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='ZIPCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
