# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170320_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
