# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('login', '0007_auto_20170322_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='author',
        ),
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
