# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170324_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject_Student',
            new_name='Subject',
        ),
    ]
