# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20170324_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
