# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20170324_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject1',
            new_name='subjectA',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject2',
            new_name='subjectB',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject3',
            new_name='subjectC',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject4',
            new_name='subjectD',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject5',
            new_name='subjectE',
        ),
    ]
