# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20170324_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectA',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectB',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectC',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectD',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectE',
            field=models.CharField(max_length=500),
        ),
    ]
