# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20170324_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subjectB',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectC',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectD',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectE',
        ),
    ]
