# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20170324_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
