# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('login', '0024_auto_20170324_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subjectA', models.CharField(blank=True, max_length=500)),
                ('subjectB', models.CharField(blank=True, max_length=500)),
                ('subjectC', models.CharField(blank=True, max_length=500)),
                ('subjectD', models.CharField(blank=True, max_length=500)),
                ('subjectE', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
