# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20170324_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject5',
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectA',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectB',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectC',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectD',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectE',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
