# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_discussionboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionboard',
            name='author',
        ),
        migrations.AddField(
            model_name='subjecta',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjecta',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjecta',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjecta',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='DiscussionBoard',
        ),
    ]
