# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20170325_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectb',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjectb',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectb',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectb',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subjectc',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjectc',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectc',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectc',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subjectd',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjectd',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectd',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectd',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subjecte',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjecte',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjecte',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjecte',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
