# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20170325_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecta',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subjecta',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='subjecta',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subjecta',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subjectb',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subjectb',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='subjectb',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subjectb',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subjectc',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subjectc',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='subjectc',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subjectc',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subjectd',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subjectd',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='subjectd',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subjectd',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='title',
        ),
        migrations.AlterField(
            model_name='subjecta',
            name='students',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectb',
            name='students',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectc',
            name='students',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectd',
            name='students',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjecte',
            name='students',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
