# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
